project:
  type: website

website:
  title: "Coding Caf√©"
  navbar:
    right:
      - icon: github
        href: https://github.com/steno-aarhus/coding-cafe
format:
  html:
    theme: cosmo
    css: styles.css
    
title-block-banner: images/banner-transparent.png

editor: 
  visual: default
  markdown: 
    wrap: 72
    canonical: true

